services:
  web:
    build: .
    container_name: user_detail_tracking
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DEBUG: "1"
      DJANGO_SETTINGS_MODULE: user_detail_tracking.settings

  db:
    image: postgres:15
    container_name: user_detail_tracking_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test321.
      POSTGRES_DB: user_detail_tracking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: user_detail_tracking_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
